# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 97fe90a78aac4db0a4131f7d20a4ca57893baad51f80a4719ade64fef09a2594bfafe8d23522e4f79002253e7b9e71f1bb84aa0ff76b665dfd3224a752b592db

test:
  secret_key_base: 612c533b6ced787824d4bdfaee5a7a38f69d84b4bf837515db343bc6a74475ac398814ea1a2f26582fbc1c37ac08b4ddb1bb78a7446161e30c970b6770cc0af0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
